#H2-Console
spring.h2.console.enabled=true
spring.datasource.platform=h2
spring.datasource.url=jdbc:h2:mem:aniket
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

#Server Port
server.port=9090

#JSP Config
spring.mvc.view.prefix=/webapp/templates/
spring.mvc.view.suffix=.jsp
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=file:src/main/webapp/